============================= test session starts =============================
platform win32 -- Python 3.11.9, pytest-8.1.1, pluggy-1.6.0 -- C:\Users\NFA\AppData\Local\Programs\Python\Python311\python.exe
cachedir: .pytest_cache
rootdir: F:\项目\实训作业\intelligent_edu_system
plugins: anyio-4.9.0, cov-4.1.0
collecting ... collected 2 items / 3 errors

=================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_aiml.py _____________________
ImportError while importing test module 'F:\项目\实训作业\intelligent_edu_system\tests\test_aiml.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Users\NFA\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\test_aiml.py:4: in <module>
    from test_api import test_login
E   ModuleNotFoundError: No module named 'test_api'
_____________________ ERROR collecting tests/test_api.py ______________________
ImportError while importing test module 'F:\项目\实训作业\intelligent_edu_system\tests\test_api.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Users\NFA\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\test_api.py:6: in <module>
    from conftest import BASE_URL
E   ModuleNotFoundError: No module named 'conftest'
_____________________ ERROR collecting tests/test_chat.py _____________________
ImportError while importing test module 'F:\项目\实训作业\intelligent_edu_system\tests\test_chat.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Users\NFA\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\test_chat.py:4: in <module>
    from conftest import BASE_URL
E   ModuleNotFoundError: No module named 'conftest'
=========================== short test summary info ===========================
ERROR tests/test_aiml.py
ERROR tests/test_api.py
ERROR tests/test_chat.py
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!
============================== 3 errors in 0.26s ==============================
